server:
 port: 8080

spring:
  application:
    name: API-GATEWAY
    
    
  main:
    allow-bean-definition-overriding: true
    
    
  cloud:
    gateway:
      routes:
      - id: STUDENT-SERVICES
        uri: lb://STUDENT-SERVICES
        predicates:
         - path=/students/**
         
      - id: MENTOR-SERVICES
        uri: lb://MENTOR-SERVICES
        predicates:
         - path=/mentors/**
         
      - id: COURSE-SERVICES
        uri: lb://COURSE-SERVICES
        predicates:
         - path=/courses/**
         
      - id: RATING-SERVICES
        uri: lb://RATING-SERVICES
        predicates:
         - path=/ratings/**
         
      - id: SUBJECT-SERVICES
        uri: lb://SUBJECT-SERVICES
        predicates:
         - path=/subjects/**
         
      - id: ADRRESS-SERVICES
        uri: lb://ADRRESS-SERVICES
        predicates:
         - path=/studentaddress/**,/mentoraddress/**
     

eureka:
  instance:
    prefer-ip-address: true 
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaulZone: http://localhost:8761/eureka
      
      
      
okta:
  oauth2:
    issuer: https://dev-37477080.okta.com/oauth2/default
    audience: api://default
    client-id: 0oag82pwz0UN7Hyfs5d7
    client-secret: 4h3-VYf1LeHgTFo7YLlH1arkuXzbOGqXDVxxoRmif1kjCulm-AIEZrUPzxZRXzK-
    scopes: openid, profile, email, offline_access