server:
  port: 8081

spring:
  application:
    name: MENTOR-SERVICES
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance: 
   prefer-ip-address: true 
   
management:
   health: 
     circuitbreakers:
        enabled: true
   endpoints:
      web:
        exposure:
         include: health
         
   endpoint:
      health: 
        show-details: always
        
resilence4j:
   circuitbreaker:
     instances:
       addressSubjectBreaker:
         registerHealthIndicator: true
         eventConsumerBufferSize: 10
         failureRateThreshould: 50
         minimumNumberOfCalls: 5
         automaticTransitionFromOpenToHalfOpenEnabled: true
         waitDurationInOpenState: 6s
         permittedNumberOfCallsInHalfOpenState: 3
         slidingWindowSize: 10
         slidingWindowType: COUNT_BASED
         
   retry:
      instances:
        addressSubjectRetry:
          max-attempts: 3
          wait-duration: 2s
          
   rateLimiter:
     instances:
        addressSubjectRateLimiter:
           limt-refresh-period: 4s
           limit-for-period: 2
           timeout-duration: 2s