server:
 port: 8084
 
spring:
  application:
    name: RATING-SERVICES
  data:
    mongodb:
     uri: mongodb://localhost:27017/microservices
    database: microservices
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:8761/eureka
  instance: 
    prefer-ip-address: true 
     